name: Build and Push Python App

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and Push to ACR
        run: |
          docker build -t acrabcreg2026test.azurecr.io/backend:${{ github.sha }} ./backend
        
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'acrabcreg2026test.azurecr.io/backend:${{ github.sha }}'
          format: 'table'
          exit-code: '1' # wenn kritische oder hohe Schwachstellen gefunden werden, soll der Schritt fehlschlagen
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Push to ACR
        if: success() # wenn scanner erfolgreich war, dann pushen
        run: |
          az acr login --name acrabcreg2026test
          docker push acrabcreg2026test.azurecr.io/backend:${{ github.sha }}

      - name: Update Manifest Repository
        run: |
          # 1. manifest repo clone
          git clone https://x-access-token:${{ secrets.MANIFEST_REPO_PAT }}@github.com/Ikayou/gitops-manifests.git
          cd gitops-manifests
          
          # 2. wechsel in das Verzeichnis, in dem die kustomization.yaml liegt
          cd ./apps/backend/overlays/staging
          
          # 3. Kustomize Befehl zum Aktualisieren des Image-Tags ausführen
          #  Beispiel: kustomize edit set image <image-name>=<new-image-tag>
          kustomize edit set image acrabcreg2026test.azurecr.io/backend:${{ github.sha }}

          cd ../production
          kustomize edit set image acrabcreg2026test.azurecr.io/backend:${{ github.sha }}

          # 4. Git Befehle zum Committen und Pushen der Änderungen ausführen
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update staging image to ${{ github.sha }}"
          git push origin main